trigger:
  branches:
    include:
      - main

pool: Default
steps:
- checkout: self

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.11'

- script: |
        python3.11 --version
        python3.11 -m pip install --upgrade pip
        python3.11 -m pip install -r requirements.txt
        pytest

- task: PublishBuildArtifacts@1
  inputs:
    pathToPublish: '$(Build.SourcesDirectory)'
    artifactName: 'python-app'

